config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :admins
  devise_for :users
  root 'home#index'
  get '/drinks' => 'drinks#index'
  get '/breakfast' => 'breakfast#index'
  get '/lunch' => 'lunch#index'
  get '/dinner' => 'dinner#index'
  get '/appetizer' => 'appetizer#index'
  get '/desserts' => 'desserts#index'
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :destroy
  has_attached_file :image, :styles => { large: "1000x500>", medium: "750x375>", thumb: "400x200>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  delegate :name, to: :category, prefix: true, allow_nil: true
  scope :breakfast, -> { where(category_id: 1) }
  scope :lunch, -> { where(category_id: 2) }
  scope :dinner, -> { where(category_id: 3) }
  scope :dessert, -> { where(category_id: 4) }
  scope :drinks, -> { where(category_id: 5) }
  scope :appetizers, -> { where(category_id: 6) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/appetizer_controller.rb
class AppetizerController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @appetizer = @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breakfast_controller.rb
class BreakfastController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @breakfast = @posts
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/desserts_controller.rb
class DessertController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @dessert = @posts
  end
end

app/controllers/dinner_controller.rb
class DinnerController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @dinner = @posts
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @sidebar = @posts.take(3)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @topsix = @posts[0..5]
    @first = @posts[6..6]
    @firstright = @posts[7..7]
    @fullwidth = @posts[8..8]
    @col8three = @posts[9..11]
    @first3 = @posts.order('created_at DESC').take(3)
    @sidebar = @posts.take(3)
    @first4 = @posts.take(4)

  end
end

app/controllers/lunch_controller.rb
class LunchController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @lunch = @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all.order('created_at DESC')
    @topsix = @posts.take(6)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /posts
  # POST /posts.json
  def create
   @post = current_user.posts.build(post_params)
   @post.category_id = params[:category_id]
     respond_to do |format|
       if @post.save
          format.html { redirect_to @post, notice: "post was successfully created." }
           format.json { render :show, status: :created, location: @post }
       else
           format.html { render :new }
           format.json { render json: @post.errors, status: :unprocessable_entity }
       end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
    @post.category_id = params[:category_id]
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :excerpt, :create_date, :author, :body, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/appetizer/index.html.erb
<div class="container page_wrapper">

  <div class="col-md-8">
    <h1>appetizer:</h1>
      <% @posts.appetizer.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
  </div>

</div>

app/views/breakfast/index.html.erb
<div class="container page_wrapper">

  <div class="col-md-8">
    <h1>Bacon Drinks:</h1>
      <% @posts.breakfast.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="container page_wrapper">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container page_wrapper">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <h3> Products under this category </h3>
  <% Post.where(category_id: @category.id).each do |post| %>
    <li> <%= post.name %> </li>
  <% end %>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
  </div>

app/views/comments/_form.html.erb
<hr />
<% form_for @comment do|f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :post_id %>

  <p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Post Comment" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/dessert/index.html.erb
<div class="container page_wrapper">

  <div class="col-md-8">
    <h1>Dessert:</h1>
      <% @posts.dessert.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
  </div>

</div>

app/views/dinner/index.html.erb
<div class="container page_wrapper">

  <div class="col-md-8">
    <h1>Dinner:</h1>
      <% @posts.dinner.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
  </div>

</div>

app/views/drinks/index.html.erb
<div class="container page_wrapper">

  <div class="col-md-8">
    <h1>Bacon Drinks:</h1>
      <% @posts.drinks.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
  </div>

</div>

app/views/home/_footer.html.erb
<div class="footer">

</div>

app/views/home/_img_left_12col.html.erb
<div class="container page_wrapper border">
  <div class="row">

    <div class="col-md-8">
      <% @first.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
      <% end %>
    </div>

    <div class="col-md-4">
      <% @first.each do |post| %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
    </div>

  </div>
</div>

app/views/home/_img_right_12col.html.erb
<div class="container page_wrapper border">
  <div class="row">

    <div class="col-md-4">
      <% @firstright.each do |post| %>
        <p class="date"><%= post.category.name %></p>
        <h1><%= link_to post.title, post %></h1>
        <h3 class="excerpt"><%= post.excerpt %></h3>
        <h5 class="author">by: <%= post.author %></h5>
      <% end %>
    </div>

    <div class="col-md-8">
      <% @firstright.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive" %>
      <% end %>
    </div>

  </div>
</div>

app/views/home/_img_top_col8.html.erb
<div class="col-md-8">
  <% @col8three.each do |post| %>
    <%= image_tag post.image.url(:large), class: "img-responsive" %>
    <p class="date"><%= post.category.name %></p>
    <h1><%= link_to post.title, post %></h1>
    <h3 class="excerpt"><%= post.excerpt %></h3>
    <h5 class="author">by: <%= post.author %></h5>
  <% end %>
</div>

app/views/home/_logo.html.erb
<div class="container">
  <div class="col-md-4 logo">
      <%= image_tag('sb.jpg', class: 'img-responsive') %>
  </div>
</div>

app/views/home/_must-read.html.erb
<div class="container must-reads">
  <h2 class="mini-title">Must Reads for January</h2>
  <div class="row no-gutter">
    <% @first4.each do |post| %>
      <div class="col-md-3"><%= image_tag post.image.url(:large), class: "img-responsive"%>
        <h5 class="small-title"><%= link_to post.title, post %></h5>
      </div>
    <% end %>
</div>

app/views/home/_post_full_width.html.erb
<div class="container page_wrapper full-width">
  <div class="row">

    <div class="col-md-12">
      <% @fullwidth.each do |post| %>
        <%= image_tag post.image.url(:large), class: "img-responsive full-width" %>
        <div class="container">
          <p class="date"><%= post.category.name %></p>
          <h1><%= link_to post.title, post %></h1>
          <h3 class="excerpt"><%= post.excerpt %></h3>
          <h5 class="author">by: <%= post.author %></h5>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/home/_sidebar.html.erb
<div class="col-md-4">
  <p><%= image_tag('wendy.jpg', class: 'img-responsive pull-right ad') %></p>
</div>

<div class="col-md-4">
  <div class="sidebar">
    <h2>Bacon Drinks:</h2>
    <% @posts.drinks.each do |post| %>
      <%= image_tag post.image.url(:thumb), class: "img-responsive" %>
      <h5 class="small-title"><%= link_to post.title, post %></h5></br></br>
    <% end %>
  </div>
</div>

app/views/home/_topsix.html.erb
<div class="row no-gutter">
  <% @topsix.each do |post| %>
    <div class="col-md-2"><%= image_tag post.image.url(:large), class: "img-responsive"%>
      <h6 class="small-title"><%= link_to post.title, post %></h6>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render 'topsix' %>
<%= render 'logo' %>
<%= render 'img_left_12col' %>
<%= render 'img_right_12col' %>
<%= render 'post_full_width' %>

<div class="container page_wrapper padding">
  <div class="row">
    <%= render 'img_top_col8' %>
    <%= render 'sidebar' %>
  </div>
</div>

<%= render 'must-read' %>
<%= render 'img_left_12col' %>
<%= render 'img_right_12col' %>
<%= render 'footer' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "Breakfast", breakfast_path %></li>
      <li><%= link_to "Lunch", lunch_path %></li>
      <li><%= link_to "Dinner", dinner_path %></li>
      <li><%= link_to "Appetizers", appetizer_path %></li>
      <li><%= link_to "Dessert", desserts_path %></li>
      <li><%= link_to "Drinks", drinks_path %></li>

    </ul>
  </div>
</nav>

<% if admin_signed_in? %>
<nav class="navbar admin-navbar" style="background-color: #fe0000;">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="navbar_admin_links"><%= link_to "New Post", new_post_path %></li>
      <li class="navbar_admin_links"><%= link_to "Sign-Up", new_user_registration_path %></li>
      <li class="navbar_admin_links"><%= link_to "Sign-Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conan</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Arapey:400,400i" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Unica+One" rel="stylesheet">

    <script src="https://cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :excerpt %>
    <%= f.text_field :excerpt %>
  </div>

  <div class="field">
    <%= f.label :create_date %>
    <%= f.date_select :create_date %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= select_tag(:category_id, options_for_select(@categories)) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Excerpt</th>
      <th>Create date</th>
      <th>Author</th>
      <th>Body</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.excerpt %></td>
        <td><%= post.create_date %></td>
        <td><%= post.author %></td>
        <td><%= image_tag post.image.url(:large) %></td>
        <td><%= post.body %></td>
        <td><%= post.category_id %></td>
        <td><%= link_to Category.find(post.category_id).name, category_path(post.category_id) %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="container page_wrapper well">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%= render 'home/topsix' %>
</div>

<div class="container page_wrapper">
  <div class="row">
    <div class="col-md-8">
      <p id="notice"><%= notice %></p>

      <p class="show_date"><%= @post.create_date %></p>
      <h1 class="show_title"><%= @post.title %></h1>
      <h4><%= @post.excerpt %></h4>
      <%= image_tag @post.image.url(:medium) %>
      <p><%= @post.author %></p>
      <p class="show_body"><%= @post.body %></p>
      <p class="well show_category"><%= @post.category.name %></p>

        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
    </div>

    <%= render 'home/sidebar' %>

  </div>
</div>